
CREATE OR REPLACE TABLE FEC.RAW.ELECTION_RESULTS_HOUSE (
    CAND_ID STRING,
    CYCLE NUMBER(4,0),
    STATE STRING,
    DISTRICT NUMBER(3,0),
    VOTES NUMBER,
    VOTE_SHARE FLOAT,
    OUTCOME NUMBER(1,0)
);


COMMENT ON TABLE FEC.RAW.ELECTION_RESULTS_HOUSE IS
'Filtered and cleaned House election results subset limited to selected general-election/FULL TERM style coverage, NOT verbatim raw FEC election returns.';



LIST @FEC.RAW.S3_STAGE/electoral/house/;


COPY INTO FEC.RAW.ELECTION_RESULTS_HOUSE
FROM (
    SELECT
        $1:CAND_ID::STRING,
        $1:CYCLE::NUMBER,
        $1:STATE::STRING,
        $1:DISTRICT::NUMBER,
        TRY_TO_NUMBER($1:VOTES::STRING) AS VOTES,
        $1:VOTE_SHARE::FLOAT,
        $1:OUTCOME::NUMBER
    FROM @FEC.RAW.S3_STAGE/electoral/house/
)
FILE_FORMAT = (TYPE = PARQUET)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';


SELECT CYCLE, COUNT(*) AS ROWS_LOADED
FROM FEC.RAW.ELECTION_RESULTS_HOUSE
GROUP BY CYCLE
ORDER BY CYCLE;

SELECT *
FROM FEC.RAW.ELECTION_RESULTS_HOUSE
ORDER BY CYCLE, STATE, DISTRICT
LIMIT 50;


SELECT
    CYCLE, STATE, DISTRICT, CAND_ID, COUNT(*) AS N
FROM FEC.RAW.ELECTION_RESULTS_HOUSE
GROUP BY CYCLE, STATE, DISTRICT, CAND_ID
HAVING COUNT(*) > 1
ORDER BY N DESC, CYCLE, STATE, DISTRICT;

SELECT
    CYCLE,
    STATE,
    DISTRICT,
    SUM(VOTE_SHARE) AS SHARE_SUM
FROM FEC.RAW.ELECTION_RESULTS_HOUSE
GROUP BY CYCLE, STATE, DISTRICT
HAVING SUM(VOTE_SHARE) < 0.85 OR SUM(VOTE_SHARE) > 1.05
ORDER BY CYCLE, STATE, DISTRICT;

SELECT
    CYCLE,
    STATE,
    DISTRICT,
    SUM(OUTCOME) AS WINNER_COUNT
FROM FEC.RAW.ELECTION_RESULTS_HOUSE
GROUP BY CYCLE, STATE, DISTRICT
HAVING SUM(OUTCOME) <> 1
ORDER BY CYCLE, STATE, DISTRICT;